MacOS x86_64 port (#65)
MacOS x86_64 port including full clang support

diff --git a/bin/tebako b/bin/tebako
--- a/bin/tebako
+++ b/bin/tebako
@@ -41,13 +41,32 @@ echo "         This command will delete all artifacts created by setup and press
 echo "         Normally you do not need to do it since tebako packager optimizes artifacts lifecycle on its own."
 }
 
+if [[ "$OSTYPE" == "linux-gnu"* ]]; then
+  echo "Setting up Linux environment"
+  gOpt="getopt"
+  uFlags="${CXXFLAGS:=}"
+elif [[ "$OSTYPE" == "darwin"* ]]; then
+  echo "Setting up MacOS environment"
+# shellcheck disable=SC2251
+  ! gOpt="$(brew --prefix gnu-getopt)/bin/getopt"
+  if [[ ${PIPESTATUS[0]} -ne 0 ]]; then
+    echo "Could not find gnu getopts, exiting"
+    exit 8
+  fi
+  uFlags="-DTARGET_OS_SIMULATOR=0 -DTARGET_OS_IPHONE=0 ${CXXFLAGS:=}"
+else
+  echo "... $OSTYPE is not supported yet, exiting"
+  exit 7
+fi
+
+
 # -allow a command to fail with !’s side effect on errexit
 # -use return value from ${PIPESTATUS[0]}, because ! hosed $?
 # shellcheck disable=SC2251
-! getopt --test > /dev/null 
+! "$gOpt" --test > /dev/null
 if [[ ${PIPESTATUS[0]} -ne 4 ]]; then
     echo "'getopt --test' failed in this environment."
-    exit 1
+   exit 1
 fi
 
 OPTIONS=hr:e:o:p:
@@ -58,12 +77,14 @@ LONGOPTS=help,root:,entry-point:,output:,prefix:
 # -activate quoting/enhanced mode (e.g. by writing out “--options”)
 # -pass arguments only via   -- "$@"   to separate them correctly
 # shellcheck disable=SC2251
-! PARSED=$(getopt --options=$OPTIONS --longoptions=$LONGOPTS --name "$0" -- "$@")
+! PARSED=$("$gOpt" --options=$OPTIONS --longoptions=$LONGOPTS --name "$0" -- "$@")
+
 if [[ ${PIPESTATUS[0]} -ne 0 ]]; then
     # e.g. return value is 1
     #  then getopt has complained about wrong arguments to stdout
     exit 2
 fi
+
 # read getopt’s output this way to handle the quoting right:
 eval set -- "$PARSED"
 
@@ -105,7 +126,7 @@ done
 # handle non-option arguments
 if [[ $# -ne 1 ]]; then
     echo "Missing command"
-    run_help    
+    run_help
     exit 4
 fi
 
@@ -120,7 +141,7 @@ fi
 
 if [[ "$prefix" == "-" ]]; then
   prefix="$( cd "$( dirname "$0" )"/.. && pwd )"
-else 
+else
   if [[ "$prefix" != /* ]]; then
     prefix="$( pwd )"/"$prefix"
   fi
@@ -132,44 +153,44 @@ export CXX=${CXX:-g++}
 case "$1" in
 	setup)
     echo "Setting up tebako at $prefix"
-    cmake -DCMAKE_BUILD_TYPE=Release   \
+    CXXFLAGS="${uFlags:=}" cmake -DCMAKE_BUILD_TYPE=Release   \
           -DDEPS:STRING="$prefix/deps" \
           -DSETUP_MODE:BOOLEAN=ON      \
           -G "Unix Makefiles"          \
           -S "$prefix"                 \
           -B "$prefix/output"	 && rc=$? || rc=$?
     if [ $rc -ne 0 ]; then
-      echo "'tebako setup' configure step failed" 
-      exit 101 
+      echo "'tebako setup' configure step failed"
+      exit 101
     fi
- 
-    cmake --build "$prefix/output" --target setup && rc=$? || rc=$?	     
+
+    CXXFLAGS="${uFlags:=}" cmake --build "$prefix/output" --target setup && rc=$? || rc=$?
     if [ $rc -ne 0 ]; then
-      echo "'tebako setup' build step failed" 
-      exit 102  
+      echo "'tebako setup' build step failed"
+      exit 102
     fi
     ;;
 	press)
     if [ "$root" == "-" ]; then
       echo "Running tebako press requires project root"
-      run_help 
-      exit 5 
+      run_help
+      exit 5
     fi
     if [ "$entryPoint" == "-" ]; then
       echo "Running tebako press requires entry point"
-      run_help 
-      exit 6 
+      run_help
+      exit 6
     fi
     if [ "$packageName" == "-" ]; then
       filename=$(basename -- "$entryPoint")
-      packageName="${filename%.*}"       
+      packageName="${filename%.*}"
     fi
 
     echo "Running tebako press at $prefix"
     echo "   Project root:            $root"
     echo "   Application entry point: $entryPoint"
     echo "   Package file name:       $packageName"
-		cmake -DCMAKE_BUILD_TYPE=Release           \
+		CXXFLAGS="${uFlags:=}" cmake -DCMAKE_BUILD_TYPE=Release           \
               -DDEPS:STRING="$prefix/deps"     \
               -DROOT:STRING="$root"            \
               -DENTRANCE:STRING="$entryPoint"  \
@@ -179,21 +200,21 @@ case "$1" in
               -S "$prefix"                     \
               -B "$prefix/output" && rc=$? || rc=$?
     if [ $rc -ne 0 ]; then
-      echo "'tebako press' configure step failed" 
-      exit 103  
+      echo "'tebako press' configure step failed"
+      exit 103
     fi
 
-    cmake --build "$prefix/output" --target tebako && rc=$? || rc=$?
-      if [[ $rc -ne 0 ]]; then
-        echo "'tebako press' build step failed" 
-        exit 104  
-      fi
+    CXXFLAGS="${uFlags:=}" cmake --build "$prefix/output" --target tebako && rc=$? || rc=$?
+    if [[ $rc -ne 0 ]]; then
+      echo "'tebako press' build step failed"
+      exit 104
+    fi
     ;;
 	clean)
     echo "Cleaning tebako setup and press artifacts at $prefix"
     rm -rf "$prefix"/output
     rm -rf "$prefix"/deps
-    ;; 
+    ;;
 	*)
 		echo "Unknown command '$1'"
 		run_help
