tebako v0.3.2 (#71)
SaasC gem hacks

diff --git a/bin/tebako b/bin/tebako
--- a/bin/tebako
+++ b/bin/tebako
@@ -1,5 +1,7 @@
 #! /bin/bash
-# This file is a part of tebako
+# Copyright (c) 2021, 2022 [Ribose Inc](https://www.ribose.com).
+# All rights reserved.
+# This file is a part of tamatebako
 #
 # Redistribution and use in source and binary forms, with or without
 # modification, are permitted provided that the following conditions
@@ -32,7 +34,7 @@ run_help() {
 echo "Usage: "
 echo "  tebako setup [-p|--prefix=<path>]"
 echo "         Tebako prefix defaults to current directory"
-echo "  tebako press [-p|--prefix=<path>] -r|--root=<path> -e|--entry-point=<path> [-o|--output=<file name>]"
+echo "  tebako press [-p|--prefix=<path>] -r|--root=<path> -e|--entry-point=<path> [-o|--output=<file name>] [-l|--log-level=<error|warn|debug>" 
 echo "         Tebako prefix defaults to current directory"
 echo "         Packaged file defaults to 'entry point' file name in the current directory"
 echo "  tebako clean [-p|--prefix=<path>]"
@@ -69,8 +71,8 @@ if [[ ${PIPESTATUS[0]} -ne 4 ]]; then
    exit 1
 fi
 
-OPTIONS=hr:e:o:p:
-LONGOPTS=help,root:,entry-point:,output:,prefix:
+OPTIONS=hr:e:o:p:l:
+LONGOPTS=help,root:,entry-point:,output:,prefix:,log-level:
 
 # -regarding ! and PIPESTATUS see above
 # -temporarily store output to be able to check for errors
@@ -88,10 +90,14 @@ fi
 # read getopt’s output this way to handle the quoting right:
 eval set -- "$PARSED"
 
-prefix=- root=- entryPoint=- packageName=-
+prefix=- root=- entryPoint=- packageName=- logLevel="error"
 # now enjoy the options in order and nicely split until we see --
 while true; do
     case "$1" in
+        -l|--log-level)
+            logLevel="$2"
+            shift 2
+            ;;
         -p|--prefix)
             prefix="$2"
             shift 2
@@ -134,6 +140,7 @@ cmk=$( which cmake )
 
 if [[ ${PIPESTATUS[0]} -ne 0 ]]; then
   echo "Failed to find cmake"
+  exit 5
 else
   echo "Using cmake at $cmk"
   cmake --version
@@ -145,6 +152,11 @@ else
   if [[ "$prefix" != /* ]]; then
     prefix="$( pwd )"/"$prefix"
   fi
+fi
+
+if [[ "$logLevel" != "error" && "$logLevel" != "warn" && "$logLevel" != "debug" && "$logLevel" != "trace" ]]; then
+  echo "Unknown log-level setting '$logLevel'. Known values are 'error', 'warn', 'debug', 'trace'"
+  exit 6
 fi
 
 export CC=${CC:-gcc}
@@ -195,6 +207,7 @@ case "$1" in
               -DROOT:STRING="$root"            \
               -DENTRANCE:STRING="$entryPoint"  \
               -DPCKG:STRING="$packageName"     \
+              -DLOG_LEVEL:STRING="$logLevel"   \
               -DSETUP_MODE:BOOLEAN=OFF         \
               -G "Unix Makefiles"              \
               -S "$prefix"                     \
