Added metanorma packaging workflow, added 3 tests from adopted ocra test set

diff --git a/bin/tebako b/bin/tebako
--- a/bin/tebako
+++ b/bin/tebako
@@ -25,11 +25,11 @@
 
 run_help() {
 echo "Usage: "
-echo "  tebako setup [-p |--prefix=<path>]"
+echo "  tebako setup [-p|--prefix=<path>]"
 echo "         Tebako prefix defaults to current directory"
-echo "  tebako press [-p |--prefix=<path>] -r |--root=<path> -e |--entry-point=<path> [-p |--package-name=<file name>]"
+echo "  tebako press [-p|--prefix=<path>] -r|--root=<path> -e|--entry-point=<path> [-o|--output=<file name>]"
 echo "         Tebako prefix defaults to current directory"
-echo "         Packaged file defaults to 'tebako'"
+echo "         Packaged file defaults to 'entry point' file name in the current directory"
 }
 
 # More safety, by turning some bugs into errors.
@@ -45,8 +45,8 @@ if [[ ${PIPESTATUS[0]} -ne 4 ]]; then
     exit 1
 fi
 
-OPTIONS=hp:c:r:e:p:
-LONGOPTS=help,prefix:,config:,root:,entry-point:,package-name:
+OPTIONS=hr:e:o:p:
+LONGOPTS=help,root:,entry-point:,output:,prefix:
 
 # -regarding ! and PIPESTATUS see above
 # -temporarily store output to be able to check for errors
@@ -61,17 +61,13 @@ fi
 # read getopt’s output this way to handle the quoting right:
 eval set -- "$PARSED"
 
-h=n prefix=- config=- root=- entryPoint=- packageName=-
+h=n prefix=- root=- entryPoint=- packageName=-
 # now enjoy the options in order and nicely split until we see --
 while true; do
     case "$1" in
         -p|--prefix)
             prefix="$2"
-            shift
-            ;;
-        -c|--config)
-            config="$2"
-            shift
+            shift 2
             ;;
         -r|--root)
             root="$2"
@@ -81,7 +77,7 @@ while true; do
             entryPoint="$2"
             shift 2
             ;;
-        -p|--package-name)
+        -o|--output)
             packageName="$2"
             shift 2
             ;;
@@ -107,7 +103,7 @@ if [ $# -ne 1 ]; then
     exit 4
 fi
 
-cmk=`which cmake`
+cmk=$( which cmake )
 
 if [ $? -ne 0 ]; then
   echo "Failed to find cmake"
@@ -125,46 +121,44 @@ export CXX=${CXX:-g++}
 
 case "$1" in
 	setup)
-        if [ "$config" == "-" ]; then
-          echo "Setting up tebako at $prefix with default configuration"  
-		else
-          echo "Setting up tebako at $prefix with custom configuration from $config"
-        fi 
-        cmake -DCMAKE_BUILD_TYPE=Release \
-              -DDEPS:STRING=$prefix/deps \
-              -DSETUP_MODE:BOOLEAN=ON    \
-              -G "Unix Makefiles"        \
-              -S $prefix                 \
-              -B $prefix/output	 && rc=$? || rc=$?
-        if [ $rc -ne 0 ]; then
-          echo "'tebako setup' configure step failed" 
-          exit 101 
-        fi
-        cmake --build $prefix/output --target setup && rc=$? || rc=$?	     
-        if [ $rc -ne 0 ]; then
-          echo "'tebako setup' build step failed" 
-          exit 102  
-        fi
-        ;;
+    echo "Setting up tebako at $prefix with custom configuration from $config"
+    cmake -DCMAKE_BUILD_TYPE=Release \
+          -DDEPS:STRING=$prefix/deps \
+          -DSETUP_MODE:BOOLEAN=ON    \
+          -G "Unix Makefiles"        \
+          -S $prefix                 \
+          -B $prefix/output	 && rc=$? || rc=$?
+    if [ $rc -ne 0 ]; then
+      echo "'tebako setup' configure step failed" 
+      exit 101 
+    fi
+ 
+    cmake --build $prefix/output --target setup && rc=$? || rc=$?	     
+    if [ $rc -ne 0 ]; then
+      echo "'tebako setup' build step failed" 
+      exit 102  
+    fi
+    ;;
 	press)
-        if [ "$root" == "-" ]; then
-          echo "Running tebako press requires project root"
-          run_help 
-          exit 5 
-		fi
-        if [ "$entryPoint" == "-" ]; then
-          echo "Running tebako press requires entry point"
-          run_help 
-          exit 6 
-		fi
-        if [ "$packageName" == "-" ]; then
-          packageName="tebako"
-		fi
+    if [ "$root" == "-" ]; then
+      echo "Running tebako press requires project root"
+      run_help 
+      exit 5 
+    fi
+    if [ "$entryPoint" == "-" ]; then
+      echo "Running tebako press requires entry point"
+      run_help 
+      exit 6 
+    fi
+    if [ "$packageName" == "-" ]; then
+      filename=$(basename -- "$entryPoint")
+      packageName="${filename%.*}"       
+    fi
 
-		echo "Running tebako press at $prefix"
-        echo "   Project root:            $root"
-        echo "   Application entry point: $entryPoint"
-        echo "   Package file name:       $packageName"
+    echo "Running tebako press at $prefix"
+    echo "   Project root:            $root"
+    echo "   Application entry point: $entryPoint"
+    echo "   Package file name:       $packageName"
 		cmake -DCMAKE_BUILD_TYPE=Release      \
               -DDEPS:STRING=$prefix/deps      \
               -DROOT:STRING=$root             \
@@ -174,17 +168,17 @@ case "$1" in
               -G "Unix Makefiles"             \
               -S $prefix                      \
               -B $prefix/output && rc=$? || rc=$?
-        if [ $rc -ne 0 ]; then
-          echo "'tebako press' configure step failed" 
-          exit 103  
-        fi
+    if [ $rc -ne 0 ]; then
+      echo "'tebako press' configure step failed" 
+      exit 103  
+    fi
 
-        cmake --build $prefix/output --target tebako && rc=$? || rc=$?
-        if [ $rc -ne 0 ]; then
-          echo "'tebako press' build step failed" 
-          exit 104  
-        fi
-        ;;
+    cmake --build $prefix/output --target tebako && rc=$? || rc=$?
+      if [ $rc -ne 0 ]; then
+        echo "'tebako press' build step failed" 
+        exit 104  
+      fi
+    ;;
 	*)
 		echo "Unknown command '$1'"
 		run_help
