chore: drop macOS-13 tests, update tools and dependencies

diff --git a/.github/workflows/macos.yml b/.github/workflows/macos.yml
--- a/.github/workflows/macos.yml
+++ b/.github/workflows/macos.yml
@@ -240,25 +240,25 @@ jobs:
         run: |
           RUBY_VER=${{ matrix.package_ruby_ver}} ruby ${{github.workspace}}/tests-2/tebako-test.rb
 
-  cross-tests:
-    needs: tests-1
-    strategy:
-      fail-fast: false
-      # Running on MacOS-14, 15 is a test for x86_64 package on arm64 system
-      matrix:
-        os: [ macos-14, macos-15 ]
-    runs-on: ${{ matrix.os }}
-    steps:
-      - name: Download test packages
-        uses: actions/download-artifact@v4
-        with:
-          name: test-packages
+#  cross-tests:
+#    needs: tests-1
+#    strategy:
+#      fail-fast: false
+#      # Running on MacOS-14, 15 is a test for x86_64 package on arm64 system
+#      matrix:
+#        os: [ macos-14, macos-15 ]
+#    runs-on: ${{ matrix.os }}
+#    steps:
+#      - name: Download test packages
+#        uses: actions/download-artifact@v4
+#        with:
+#          name: test-packages
 
-      - name: Run test packages
-        run:  |
-          set -o errexit -o pipefail -o noclobber -o nounset
-          chmod +x test-*-package
-          for TP in test-*-package; do "./$TP"; done
+#      - name: Run test packages
+#        run:  |
+#          set -o errexit -o pipefail -o noclobber -o nounset
+#          chmod +x test-*-package
+#          for TP in test-*-package; do "./$TP"; done
 
   integration-test:
     needs: tests-1
