Adopt script that discovers and packages ruby dependencies (#20)

diff --git a/.github/workflows/ubuntu-build.yml b/.github/workflows/ubuntu-build.yml
--- a/.github/workflows/ubuntu-build.yml
+++ b/.github/workflows/ubuntu-build.yml
@@ -4,8 +4,16 @@ on:
   # Triggers the workflow on push or pull request events but only for the master branch
   push:
     branches: [ master, issue-1 ]
+    paths-ignore:
+      - 'docs/**'
+      - '**.adoc'
+      - '**.md'
   pull_request:
     branches: [ master ]
+    paths-ignore:
+      - 'docs/**'
+      - '**.adoc'
+      - '**.md'
 
   # Allows you to run this workflow manually from the Actions tab
   workflow_dispatch:
@@ -43,6 +51,7 @@ env:
 jobs:
   Ubuntu-build:
     runs-on: ubuntu-latest
+    if: "!contains(github.event.head_commit.message, 'skip ci')"
 
     steps:
     - uses: actions/checkout@v2
@@ -66,10 +75,11 @@ jobs:
     - uses: actions/cache@v2
       with:
         path: ${{github.workspace}}/${{env.DEPS}}
-        key: ${{ github.workflow }}-${{ hashFiles('key.txt') }}-v9
+        key: ${{ github.workflow }}-${{ hashFiles('key.txt') }}-v15
 
     - name: Install packages Ubuntu
-# Already installed: bison flex fuse3 pkg-config 
+# Already installed: bison flex fuse3 pkg-config
+# libsqlite3-dev  is required for Rails packaging tests only
       run: |
         sudo apt-get update
         sudo apt-get install \
@@ -77,24 +87,196 @@ jobs:
         libdouble-conversion-dev libiberty-dev liblz4-dev liblzma-dev libssl-dev \
         libboost-context-dev libboost-filesystem-dev libboost-program-options-dev \
         libboost-regex-dev libboost-system-dev libboost-thread-dev \
-        libunwind-dev libdwarf-dev libelf-dev libfmt-dev libfuse3-dev libgoogle-glog-dev 
+        libunwind-dev libdwarf-dev libelf-dev libfmt-dev libfuse3-dev libgoogle-glog-dev \
+        libsqlite3-dev
         
-    - name: CMake Configure
-      run: | 
-        cmake -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}                 \
-              -DDEPS:STRING=${{github.workspace}}/${{env.DEPS}}      \
-              -DDWARFS_TAG:STRING=${{env.DWARFS_TAG}}                \
-              -DINCBIN_TAG:STRING=${{env.INCBIN_TAG}}                \
-              -B ${{github.workspace}}
-                                            
-    - name: CMake build and install
-      run: cmake --build ${{github.workspace}} --config ${{env.BUILD_TYPE}} --target install
-
     - name: Create mount point
       run: |
         sudo mkdir -p /home/tebako 
         sudo chmod a+w /home/tebako
-        sudo chmod g+w /home/tebako
 
-    - name: Run
-      run: sudo /usr/local/bin/tebako
+# Tests
+#  01. [Also the baseline] Simple Ruby script, relative path to entry point  
+#  02. Simple Ruby script, relative path to entry point, non exisitng entrance      Expected error at configure step
+#  03. Simple Ruby script, absolute path to entry point 
+#  04. Simple Ruby script, absolute path to entry point, relative path to root      
+#  05. Simple Ruby script, absolute path to entry point, not within root            Expected error at configure step
+#  06. Rails project                                                                
+#  07. Rails project, ruby and bundler version mismatch                             Expected error at build step
+#  08. Rails project, no entry point                                                Expected error at build step           [TODO]
+#  09. Ruby gem (xxx.gem file)  
+#  10. Ruby gem (xxx.gem file), no entry point                                      Expected error at build step
+#  11. Ruby gem, no gemfile, with gemspec                                             
+#  12. Ruby gem, no gemfile, multiple gemspecs                                      Expected error at configure step
+#  13. Ruby gem, no gemfile, gemspec error                                          Expected error at build step  
+#  14. Ruby gem, no gemfile, gemspec, no entry point                                Expected error at build step  
+#  15. Ruby gem, gemfile, gemspec                                             
+#  16. Ruby gem, gemfile, gemspec error                                             Expected error at build step  
+#  17. Ruby gem, gemfile, gemspec, no entry point                                   Expected error at build step  
+#
+
+    - name: Baseline & Test01 - Configure - [Simple Ruby script, relative path to entry point]
+      run: | 
+        cmake -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}                 \
+              -DDEPS:STRING=${{github.workspace}}/${{env.DEPS}}      \
+              -DROOT="${{github.workspace}}/tests/test-01" -DENTRANCE="test.rb"           \
+              -B ${{github.workspace}}
+                                            
+    - name: Test01 - Build and install packaged solution - [Simple Ruby script, relative path to entry point]
+      run: cmake --build ${{github.workspace}} --config ${{env.BUILD_TYPE}} --target install
+
+    - name: Test01 - Run packaged solution - [Simple Ruby script, relative path to entry point]
+      run:  /usr/local/bin/tebako
+#        echo Tebako exit code $?
+
+    - name: Test02 - Configure[only] - [Simple Ruby script, relative path to entry point, non exisitng entrance]
+      run: | 
+        ${{github.workspace}}/.github/scripts/configure_with_failure.sh        \
+              ${{env.BUILD_TYPE}} ${{github.workspace}}/${{env.DEPS}}          \
+              "${{github.workspace}}/tests/test-01" "test-does-not-exist.rb"    \
+              ${{github.workspace}}
+              
+    - name: Test03 - Configure - [Simple Ruby script, absolute path to entry point]
+      run: | 
+        cmake -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}                 \
+              -DDEPS:STRING=${{github.workspace}}/${{env.DEPS}}      \
+              -DROOT="${{github.workspace}}/tests/test-01" -DENTRANCE="${{github.workspace}}/tests/test-01/test.rb"           \
+              -B ${{github.workspace}}
+                                            
+    - name: Test03 - Build and install packaged solution - [Simple Ruby script, absolute path to entry point]
+      run: cmake --build ${{github.workspace}} --config ${{env.BUILD_TYPE}} --target install
+
+    - name: Test03 - Run packaged solution - [Simple Ruby script, absolute path to entry point]
+      run:  /usr/local/bin/tebako
+
+    - name: Test04 - Configure[only] - [Simple Ruby script, absolute path to entry point, relative path to root ]
+      run: | 
+        cmake -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}                 \
+              -DDEPS:STRING=${{github.workspace}}/${{env.DEPS}}      \
+              -DROOT="tests/test-01" -DENTRANCE="test.rb"           \
+              -B ${{github.workspace}}
+                                            
+    - name: Test04 - Build and install packaged solution - [Simple Ruby script, absolute path to entry point, relative path to root ]
+      run: cmake --build ${{github.workspace}} --config ${{env.BUILD_TYPE}} --target install
+
+    - name: Test04 - Run packaged solution - [Simple Ruby script, absolute path to entry point, relative path to root ]
+      run:  /usr/local/bin/tebako
+                                           
+    - name: Test05 - Configure[only] - [Simple Ruby script, absolute path to entry point, not within root]
+      run: | 
+        ${{github.workspace}}/.github/scripts/configure_with_failure.sh       \
+              ${{env.BUILD_TYPE}} ${{github.workspace}}/${{env.DEPS}}         \
+              "${{github.workspace}}/tests/test-01" "${{github.workspace}}/tests/test-00/test.rb" \
+              ${{github.workspace}}
+
+    - name: Test06 - Configure - [Rails project]
+      run: | 
+        cmake -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}                 \
+              -DDEPS:STRING=${{github.workspace}}/${{env.DEPS}}      \
+              -DROOT="${{github.workspace}}/tests/test-06" -DENTRANCE="test.rb"           \
+              -B ${{github.workspace}}
+    
+    - name: Test07 - Configure - [Rails project, ruby and bundler version mismatch]
+      run: | 
+        cmake -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}                 \
+              -DDEPS:STRING=${{github.workspace}}/${{env.DEPS}}      \
+              -DROOT="${{github.workspace}}/tests/test-07" -DENTRANCE="test.rb"           \
+              -B ${{github.workspace}}
+
+    - name: Test07 - Build - [Rails project, ruby and bundler version mismatch]
+      run:  ${{github.workspace}}/.github/scripts/build_with_failure.sh ${{github.workspace}} ${{env.BUILD_TYPE}}
+
+    - name: Test09 - Configure - [xxx.gem, no gemspec, no gemfile]
+      run: | 
+        cmake -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}                 \
+              -DDEPS:STRING=${{github.workspace}}/${{env.DEPS}}      \
+              -DROOT="${{github.workspace}}/tests/test-09" -DENTRANCE="tebako-test-run.rb"     \
+              -B ${{github.workspace}}
+
+    - name: Test09 - Build and install packaged solution - [xxx.gem, no gemspec, no gemfile]
+      run: cmake --build ${{github.workspace}} --config ${{env.BUILD_TYPE}} --target install
+
+    - name: Test09 - Run packaged solution - [xxx.gem, no gemspec, no gemfile]
+      run:  /usr/local/bin/tebako
+
+    - name: Test10 - Configure - [xxx.gem, no gemspec, no gemfile, entry point does not exist]
+      run: | 
+        cmake -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}                 \
+              -DDEPS:STRING=${{github.workspace}}/${{env.DEPS}}      \
+              -DROOT="${{github.workspace}}/tests/test-09" -DENTRANCE="tebako-test-no-entry-point.rb"     \
+              -B ${{github.workspace}}
+
+    - name: Test10 - Build - [xxx.gem, no gemspec, no gemfile, entry point does not exist]
+      run: ${{github.workspace}}/.github/scripts/build_with_failure.sh ${{github.workspace}} ${{env.BUILD_TYPE}} 
+
+    - name: Test11 - Configure - [Ruby gem, gemspec, no gemfile]
+      run: | 
+        cmake -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}                 \
+              -DDEPS:STRING=${{github.workspace}}/${{env.DEPS}}      \
+              -DROOT="${{github.workspace}}/tests/test-11" -DENTRANCE="tebako-test-run.rb"     \
+              -B ${{github.workspace}}
+
+    - name: Test11 - Build and install packaged solution - [Ruby gem, no gemfile]
+      run: cmake --build ${{github.workspace}} --config ${{env.BUILD_TYPE}} --target install
+
+    - name: Test11 - Run packaged solution - [Ruby gem, no gemfile]
+      run:  /usr/local/bin/tebako
+
+    - name: Test12 - Configure[only] - [Ruby gem, multiple gemspecs]
+      run: | 
+        ${{github.workspace}}/.github/scripts/configure_with_failure.sh       \
+              ${{env.BUILD_TYPE}} ${{github.workspace}}/${{env.DEPS}}         \
+              "${{github.workspace}}/tests/test-12" "tebako-test-run.rb"      \
+              ${{github.workspace}}
+
+    - name: Test13 - Configure - [Ruby gem, no gemfile, gemspec error]
+      run: | 
+        cmake -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}                 \
+              -DDEPS:STRING=${{github.workspace}}/${{env.DEPS}}      \
+              -DROOT="${{github.workspace}}/tests/test-13" -DENTRANCE="tebako-test-run.rb"    \
+              -B ${{github.workspace}}
+
+    - name: Test13 - Build and install packaged solution - [Ruby gem, no gemfile, gemspec error]
+      run:  ${{github.workspace}}/.github/scripts/build_with_failure.sh ${{github.workspace}} ${{env.BUILD_TYPE}}
+
+    - name: Test14 - Configure - [Ruby gem, gemspec, no gemfile, entry point does not exist]
+      run: | 
+        cmake -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}                 \
+              -DDEPS:STRING=${{github.workspace}}/${{env.DEPS}}      \
+              -DROOT="${{github.workspace}}/tests/test-11" -DENTRANCE="tebako-test-no-entry-point.rb"     \
+              -B ${{github.workspace}}
+
+
+    - name: Test15 - Configure - [Ruby gem, gemspec, gemfile]
+      run: | 
+        cmake -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}                 \
+              -DDEPS:STRING=${{github.workspace}}/${{env.DEPS}}      \
+              -DROOT="${{github.workspace}}/tests/test-15" -DENTRANCE="tebako-test-run.rb"     \
+              -B ${{github.workspace}}
+
+    - name: Test15 - Build and install packaged solution - [Ruby gem, gemspec, gemfile]
+      run: cmake --build ${{github.workspace}} --config ${{env.BUILD_TYPE}} --target install
+
+    - name: Test15 - Run packaged solution - [Ruby gem, gemspec, gemfile]
+      run:  /usr/local/bin/tebako
+
+    - name: Test16 - Configure - [Ruby gem, gemspec, gemfile with error]
+      run: | 
+        cmake -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}                 \
+              -DDEPS:STRING=${{github.workspace}}/${{env.DEPS}}      \
+              -DROOT="${{github.workspace}}/tests/test-16" -DENTRANCE="tebako-test-run.rb"     \
+              -B ${{github.workspace}}
+
+    - name: Test16 - Build and install packaged solution - [Ruby gem, gemspec, gemfile with error]
+      run:  ${{github.workspace}}/.github/scripts/build_with_failure.sh ${{github.workspace}} ${{env.BUILD_TYPE}}
+
+    - name: Test17 - Configure - [Ruby gem, gemspec, gemfile, entry point does not exist]
+      run: | 
+        cmake -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}                 \
+              -DDEPS:STRING=${{github.workspace}}/${{env.DEPS}}      \
+              -DROOT="${{github.workspace}}/tests/test-15" -DENTRANCE="tebako-test-run-no-entry.rb"     \
+              -B ${{github.workspace}}
+
+    - name: Test17 - Build and install packaged solution - [Ruby gem, gemspec, gemfile, entry point does not exist]
+      run: ${{github.workspace}}/.github/scripts/build_with_failure.sh ${{github.workspace}} ${{env.BUILD_TYPE}} 
+
