Ruby gem, no gemfile

diff --git a/.github/workflows/ubuntu-build.yml b/.github/workflows/ubuntu-build.yml
--- a/.github/workflows/ubuntu-build.yml
+++ b/.github/workflows/ubuntu-build.yml
@@ -91,8 +91,9 @@ jobs:
 #   5. Simple Ruby script, absolute path to entry point, not within root            Expected error at configure step
 #   6-10  reserved
 #  11. Ruby gem, no gemfile
-#  12. Ruby gem, multiple gemspecs                                                  Expected error at configure step
-#  13. Ruby gem, gemspec error                                                      Expected error at build step  
+#  12. Ruby gem, no gemfile, multiple gemspecs                                      Expected error at configure step
+#  13. Ruby gem, no gemfile, gemspec error                                          Expected error at build step  
+#  13. Ruby gem, no gemfile, no entry point                                         Expected error at build step  
 #
 
     - name: Baseline & Test1 - Configure - [Simple Ruby script, relative path to entry point]
@@ -108,7 +109,7 @@ jobs:
     - name: Test1 - Run packaged solution - [Simple Ruby script, relative path to entry point]
       run:  |
         /usr/local/bin/tebako
-        echo $?
+#        echo Tebako exit code $?
 
     - name: Test2 - Configure[only] - [Simple Ruby script, relative path to entry point, non exisitng entrance]
       run: | 
@@ -128,7 +129,7 @@ jobs:
       run: cmake --build ${{github.workspace}} --config ${{env.BUILD_TYPE}} --target install
 
     - name: Test3 - Run packaged solution - [Simple Ruby script, absolute path to entry point]
-      run: sudo /usr/local/bin/tebako
+      run:  /usr/local/bin/tebako
 
     - name: Test4 - Configure[only] - [Simple Ruby script, absolute path to entry point, relative path to root ]
       run: | 
@@ -141,32 +142,42 @@ jobs:
       run: | 
         ${{github.workspace}}/.github/scripts/configure_with_failure.sh       \
               ${{env.BUILD_TYPE}} ${{github.workspace}}/${{env.DEPS}}         \
-              "${{github.workspace}}/tests/test-1" "${{github.workspace}}/tests/test-0/test.rb"                \
+              "${{github.workspace}}/tests/test-1" "${{github.workspace}}/tests/test-0/test.rb" \
               ${{github.workspace}}
 
     - name: Test11 - Configure - [Ruby gem, no gemfile]
       run: | 
         cmake -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}                 \
               -DDEPS:STRING=${{github.workspace}}/${{env.DEPS}}      \
-              -DROOT="${{github.workspace}}/tests/test-11" -DENTRANCE="test.rb"           \
+              -DROOT="${{github.workspace}}/tests/test-11" -DENTRANCE="tebako-test-run.rb"     \
               -B ${{github.workspace}}
 
     - name: Test11 - Build and install packaged solution - [Ruby gem, no gemfile]
       run: cmake --build ${{github.workspace}} --config ${{env.BUILD_TYPE}} --target install
 
+    - name: Test11 - Run packaged solution - [Ruby gem, no gemfile]
+      run:  /usr/local/bin/tebako
+
     - name: Test12 - Configure[only] - [Ruby gem, no gemfile, multiple gemspecs]
       run: | 
         ${{github.workspace}}/.github/scripts/configure_with_failure.sh       \
               ${{env.BUILD_TYPE}} ${{github.workspace}}/${{env.DEPS}}         \
-              "${{github.workspace}}/tests/test-12" "test.rb"               \
+              "${{github.workspace}}/tests/test-12" "tebako-test-run.rb"      \
               ${{github.workspace}}
 
     - name: Test13 - Configure - [Ruby gem, no gemfile, gemspec error]
       run: | 
         cmake -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}                 \
               -DDEPS:STRING=${{github.workspace}}/${{env.DEPS}}      \
-              -DROOT="${{github.workspace}}/tests/test-13" -DENTRANCE="test.rb"           \
+              -DROOT="${{github.workspace}}/tests/test-13" -DENTRANCE="tebako-test-run.rb"    \
               -B ${{github.workspace}}
 
-    - name: Test13 - Build and install packaged solution - [Ruby gem, gemspec error]
+    - name: Test13 - Build and install packaged solution - [Ruby gem, no gemfile, gemspec error]
       run:  ${{github.workspace}}/.github/scripts/build_with_failure.sh ${{github.workspace}} ${{env.BUILD_TYPE}}
+
+    - name: Test14 - Configure[only] - [Ruby gem, no gemfile, entry point does not exist]
+      run: | 
+        ${{github.workspace}}/.github/scripts/configure_with_failure.sh       \
+              ${{env.BUILD_TYPE}} ${{github.workspace}}/${{env.DEPS}}         \
+              "${{github.workspace}}/tests/test-11" "tebako-test-no-entry-point.rb"      \
+              ${{github.workspace}}
